'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SipPhone.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property hangup_wav() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hangup.wav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend ReadOnly Property lame_enc_dll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lame_enc.dll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на This software is provided &apos;as-is&apos;, without any express or implied warranty.
        '''In no event will the authors be held liable for any damages arising from the
        '''use of this software.
        '''
        '''
        '''                    GNU GENERAL PUBLIC LICENSE
        '''                       Version 2, June 1991
        '''
        ''' Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        ''' 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not al [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property License_txt() As String
            Get
                Return ResourceManager.GetString("License.txt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend ReadOnly Property microsip_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("microsip.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на [Settings]
        '''accountId=1
        '''singleMode=1
        '''ringingSound=ringing.wav
        '''volumeRing=100
        '''audioRingDevice=&quot;&quot;
        '''audioOutputDevice=&quot;&quot;
        '''audioInputDevice=&quot;&quot;
        '''micAmplification=0
        '''swLevelAdjustment=0
        '''audioCodecs=PCMA/8000/1 PCMU/8000/1
        '''VAD=0
        '''EC=1
        '''forceCodec=0
        '''opusStereo=0
        '''disableMessaging=1
        '''rport=1
        '''sourcePort=0
        '''rtpPortMin=0
        '''rtpPortMax=0
        '''dnsSrvNs=
        '''dnsSrv=0
        '''enableSTUN=0
        '''recordingPath=Recordings
        '''recordingFormat=mp3
        '''autoRecording=0
        '''recordingButton=0
        '''DTMFMethod=0
        '''autoAnswer=
        '''autoAnswerDelay=0
        '''autoAnswerNumb [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property microsip_ini() As String
            Get
                Return ResourceManager.GetString("microsip.ini", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property msgin_wav() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("msgin.wav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property msgout_wav() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("msgout.wav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ringing_wav() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ringing.wav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ringing2_wav() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ringing2.wav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ringtone_wav() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ringtone.wav", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
